source-file ~/.config/tmux/keys.conf

#  Fix terminal coloring
set -ga terminal-overrides ",xterm-256color:Tc"
set -g mode-keys vi

# Copying to system clipboard
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel "xclip -selection clipboard -in"

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Open split windows in the current path
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

set -g mouse on
set -g status-position bottom

# ------------------ Appearance
set -g @catppuccin_flavor 'macchiato'
set -g @catppuccin_window_status_style 'slanted'

set -g @catppuccin_window_text " #W"
set -g @catppuccin_window_current_text " #W"

run '~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux'

set -g status on
set -g status-position top
set -g status-left ""

set -g status-right "#{host} [#{session_name}]"

# ----------------- List of plugins
set -g @plugin 'tmux-plugins/tpm'
# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/plugins/tpm/tpm'

