[[mgr.prepend_keymap]]
on = "<Enter>"
run = "plugin smart-enter"
desc = "Enter the directory or open the file under the cursor"

[[mgr.prepend_keymap]]
on = "-"
run = "leave"
desc = "Go back to the previous directory"

[[mgr.prepend_keymap]]
on = [ "m" ]
run = "plugin relative-motions"
desc = "Trigger a new relative motion"
